import type { CatalogEntry } from './catalog-entry';

/**
 * Curated seed catalog, roughly ordered by popularity (ties in search break toward the
 * top). Prices are indicative defaults in the listed currency and are user-editable.
 * Extend via app releases; a signed remote refresh can come later (feat-catalog).
 */
export const CATALOG: readonly CatalogEntry[] = [
  {
    id: 'netflix',
    name: 'Netflix',
    aliases: [],
    category: 'Streaming',
    amountMinor: 1799,
    currency: 'EUR',
    cycle: 'monthly',
  },
  {
    id: 'spotify',
    name: 'Spotify',
    aliases: [],
    category: 'Music',
    amountMinor: 1099,
    currency: 'EUR',
    cycle: 'monthly',
  },
  {
    id: 'amazon-prime',
    name: 'Amazon Prime',
    aliases: ['prime'],
    category: 'Shopping',
    amountMinor: 8990,
    currency: 'EUR',
    cycle: 'annual',
  },
  {
    id: 'disney-plus',
    name: 'Disney+',
    aliases: ['disney plus', 'disney'],
    category: 'Streaming',
    amountMinor: 899,
    currency: 'EUR',
    cycle: 'monthly',
  },
  {
    id: 'youtube-premium',
    name: 'YouTube Premium',
    aliases: ['youtube'],
    category: 'Streaming',
    amountMinor: 1299,
    currency: 'EUR',
    cycle: 'monthly',
  },
  {
    id: 'apple-music',
    name: 'Apple Music',
    aliases: [],
    category: 'Music',
    amountMinor: 1099,
    currency: 'EUR',
    cycle: 'monthly',
  },
  {
    id: 'icloud-plus',
    name: 'iCloud+',
    aliases: ['icloud'],
    category: 'Storage',
    amountMinor: 299,
    currency: 'EUR',
    cycle: 'monthly',
  },
  {
    id: 'google-one',
    name: 'Google One',
    aliases: ['google drive'],
    category: 'Storage',
    amountMinor: 199,
    currency: 'EUR',
    cycle: 'monthly',
  },
  {
    id: 'hbo-max',
    name: 'HBO Max',
    aliases: ['max', 'hbo'],
    category: 'Streaming',
    amountMinor: 999,
    currency: 'EUR',
    cycle: 'monthly',
  },
  {
    id: 'microsoft-365',
    name: 'Microsoft 365',
    aliases: ['office 365', 'office'],
    category: 'Productivity',
    amountMinor: 6900,
    currency: 'EUR',
    cycle: 'annual',
  },
  {
    id: 'adobe-cc',
    name: 'Adobe Creative Cloud',
    aliases: ['adobe', 'creative cloud'],
    category: 'Creative',
    amountMinor: 6099,
    currency: 'EUR',
    cycle: 'monthly',
  },
  {
    id: 'notion',
    name: 'Notion',
    aliases: [],
    category: 'Productivity',
    amountMinor: 900,
    currency: 'USD',
    cycle: 'monthly',
  },
  {
    id: 'chatgpt-plus',
    name: 'ChatGPT Plus',
    aliases: ['openai', 'chatgpt'],
    category: 'AI',
    amountMinor: 2000,
    currency: 'USD',
    cycle: 'monthly',
  },
  {
    id: 'claude-pro',
    name: 'Claude Pro',
    aliases: ['anthropic', 'claude'],
    category: 'AI',
    amountMinor: 2000,
    currency: 'USD',
    cycle: 'monthly',
  },
  {
    id: 'github',
    name: 'GitHub Pro',
    aliases: ['github'],
    category: 'Developer',
    amountMinor: 400,
    currency: 'USD',
    cycle: 'monthly',
  },
  {
    id: 'xbox-game-pass',
    name: 'Xbox Game Pass',
    aliases: ['game pass', 'xbox'],
    category: 'Gaming',
    amountMinor: 1499,
    currency: 'EUR',
    cycle: 'monthly',
  },
  {
    id: 'playstation-plus',
    name: 'PlayStation Plus',
    aliases: ['ps plus', 'psn'],
    category: 'Gaming',
    amountMinor: 899,
    currency: 'EUR',
    cycle: 'monthly',
  },
  {
    id: 'nintendo-online',
    name: 'Nintendo Switch Online',
    aliases: ['nintendo'],
    category: 'Gaming',
    amountMinor: 1999,
    currency: 'EUR',
    cycle: 'annual',
  },
  {
    id: 'paramount-plus',
    name: 'Paramount+',
    aliases: ['paramount'],
    category: 'Streaming',
    amountMinor: 799,
    currency: 'EUR',
    cycle: 'monthly',
  },
  {
    id: 'audible',
    name: 'Audible',
    aliases: [],
    category: 'Audiobooks',
    amountMinor: 999,
    currency: 'EUR',
    cycle: 'monthly',
  },
  {
    id: 'dropbox',
    name: 'Dropbox',
    aliases: [],
    category: 'Storage',
    amountMinor: 1199,
    currency: 'EUR',
    cycle: 'monthly',
  },
  {
    id: 'linkedin-premium',
    name: 'LinkedIn Premium',
    aliases: ['linkedin'],
    category: 'Career',
    amountMinor: 2999,
    currency: 'EUR',
    cycle: 'monthly',
  },
  {
    id: 'duolingo',
    name: 'Duolingo',
    aliases: ['duolingo super'],
    category: 'Education',
    amountMinor: 1299,
    currency: 'EUR',
    cycle: 'monthly',
  },
  {
    id: 'nordvpn',
    name: 'NordVPN',
    aliases: ['nord vpn', 'nord'],
    category: 'VPN',
    amountMinor: 1299,
    currency: 'EUR',
    cycle: 'monthly',
  },
  {
    id: '1password',
    name: '1Password',
    aliases: ['1 password'],
    category: 'Security',
    amountMinor: 299,
    currency: 'EUR',
    cycle: 'monthly',
  },
  {
    id: 'zoom',
    name: 'Zoom',
    aliases: [],
    category: 'Productivity',
    amountMinor: 1399,
    currency: 'EUR',
    cycle: 'monthly',
  },
  {
    id: 'canva',
    name: 'Canva',
    aliases: ['canva pro'],
    category: 'Creative',
    amountMinor: 1199,
    currency: 'EUR',
    cycle: 'monthly',
  },
  {
    id: 'twitch',
    name: 'Twitch Turbo',
    aliases: ['twitch'],
    category: 'Streaming',
    amountMinor: 899,
    currency: 'EUR',
    cycle: 'monthly',
  },
  {
    id: 'patreon',
    name: 'Patreon',
    aliases: [],
    category: 'Creators',
    amountMinor: 500,
    currency: 'USD',
    cycle: 'monthly',
  },
  {
    id: 'strava',
    name: 'Strava',
    aliases: [],
    category: 'Fitness',
    amountMinor: 799,
    currency: 'EUR',
    cycle: 'monthly',
  },
];
