// @ts-check
import js from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/build/**',
      '**/coverage/**',
      '**/web-build/**',
      '**/.expo/**',
      // Generated by the test/mutation tooling — never source.
      '**/.stryker-tmp/**',
      '**/reports/**',
      // Tooling configs are not part of any tsconfig project, so type-aware linting
      // cannot parse them. Covers `*.config.*` plus dot-prefixed CJS configs
      // (.lintstagedrc.cjs, .dependency-cruiser.cjs).
      '**/*.config.*',
      '**/.*.cjs',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-non-null-assertion': 'error',
      '@typescript-eslint/consistent-type-imports': 'error',
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/switch-exhaustiveness-check': 'error',
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      eqeqeq: ['error', 'always'],
    },
  },
  {
    // The domain core must stay pure: forbid framework/platform imports.
    files: ['packages/domain/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            'react',
            'react-*',
            'react-native',
            'react-native-*',
            'expo',
            'expo-*',
            '@op-engineering/*',
            'drizzle-orm',
            'drizzle-orm/*',
          ],
        },
      ],
    },
  },
  {
    // Tests may use looser typing ergonomics.
    files: ['**/*.test.ts', '**/*.spec.ts'],
    rules: {
      '@typescript-eslint/no-non-null-assertion': 'off',
    },
  },
);
